language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=https://pinarlabs.pactflow.io
  - PACT_BROKER_BASE_URL=https://engineering-services-pact-service.kbuild-dev.msap.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "ZM0ini0DJyhpJ2apKCNxfbs3PHRj16WXqGokSBywLMlEG/9UHxt7fRzFoGjbfaOUecaQ+NlGd4x3FlDhJ5/XixI1MQx8nC7QmMLiP/SpIq1O2GCUGGuCkf1oLU/IvziC7AabYTiseb8xcpn0ju5mK+YQreu/3j9hRog8V2okH8w6gT+3LhKb+9j0FVTYyJqO+K/ipE7HjhCOeT5jcY098zBrebfBi1C/Mopm1x9x7Lxc5qnPrSH235y/PcheJYbOBZAtM0ZbdLoTC/j41DcEwTraph0M2R1J7JA+e/28ybvDPebY4jocUGCScpQZ1cbH01kDVni7kiqqye/s5raCmbNOGjlX045Zi7iAM7ciJSueRuTHBdFjAxWBJti/A10LHWGX0tjNjIL42ZEC4YIVmGuWRLTux6Ae1MswDK+GfDvzoOVsn7wyF2iS8eHe2/3EZ98cBeIROfVAYhv21WN3Yw2dBSAEA5ceS9Cwz8Ikp2uyu9OF3z33dwM0xwrs0PuuOe7VhugfUEjQwmElfBvJArLmpgYsLU6uUvWP5J2VifaWLv+h27AjxyfWyPf4s9q7KMRhvL/bE0P7cDCjV5nRcJN7kePRTWq/JcTvl2Uq5e/n0Bn/GNSwUH3HxxQf8oD7IvxkhMvb0PdYHL3DrcjxdJ1RhHFmjRiE6iI8/p23/Fw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
